apiVersion: v1
kind: Service
metadata:
  name: demo-clusterip
spec:
  type: ClusterIP
  selector:
    app: service-demo
    service-type: clusterip
  ports:
    - name: http
      port: 80
      targetPort: 8000
