apiVersion: v1
kind: Service
metadata:
  name: demo-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: service-demo
    service-type: loadbalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
